title: "Bri Rowe"
description: "Personal website for research, education, experience, and creative projects."
url: "https://brirowe.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
